[goldmark]
  [goldmark.extensions]
    typographer = false
  [goldmark.renderer]
    unsafe = true
[highlight]
  codeFences = true
  guessSyntax = false
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2
[tableOfContents]
  endLevel = 4
  ordered = true
  startLevel = 2
