# -- Main Menu --
# The top menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]

[[top]]
  name = "Main Menu"

[[top]]
  name = "HarryPedia"
  pageRef = "harrypedia"
  weight = 10
  parent = "Main Menu"

[[top]]
  name = "Searches"
  pageRef = "searches"
  weight = 20
  parent = "Main Menu"

[[top]]
  name = "Bookmarks"
  pageRef = "bookmarks"
  weight = 30
  parent = "Main Menu"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the top menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
