mainSections = ["Harrypedia"] # use it for blog page section 

uniqueHomePage = true # change to false to add sidebar to homepage

# Site logo
[logo]
  lightMode = "images/compose.svg"
  darkMode = "images/compose-light.svg"

author = "Luke Schierer"

disableMermaid = false

# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"

# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "blue"

# see https://learn.netlify.app/en/basics/configuration/ for more theme specific options
