baseURL = "http://hpfan.luke.schierer.org/"
languageCode = "en-GB"
title = "Harry Potter Analysis, Speculation, Fan fiction, and Fan fiction tracking"
copyright = "© 2005-2022 Luke Schierer"
owner = "Luke Schierer"
theme = "terminal"

