baseURL = "https://hpfan.schierer.org/"
languageCode = "en-GB"
title = "Harry Potter Notes, Analysis, Speculation, Fan fiction, and Fan fiction tracking"
copyright = "© 2005-2022 Luke Schierer"
owner = "Luke Schierer"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = "congo"
enableGitInfo = true

[frontmatter]
  date = [":git", ":filename", "publishDate", "lastmod", "date" ]

disablePathToLower = true

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#googleAnalytics = "G-9KF1R3YFTZ"
id = "G-9KF1R3YFTZ"

