/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "HP-Stuff-Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "HP-Stuff-Static": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "gedcom-event": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "gedcom-events": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "gedcom-families": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "gedcom-family": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "gedcom-people": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "gedcom-person": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}