[languages.en]
  languageName = "English"
  title = "Luke's Harry Potter Fan Site"
  subtitle = "Analysis, Speculation, Fan fiction, and Fan fiction tracking"
  keywords = ""
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"
