name: infrastructure
description: hpfan.schierer infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: container-aws-typescript
